# Generated by Django 4.1 on 2022-08-24 17:44

import datetime
from django.db import migrations, models
import sensor.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='PSSR', max_length=200, validators=[sensor.models.mustStartWithPSSR])),
                ('installation_date', models.DateField(default=datetime.date(2022, 8, 24), verbose_name='date installation')),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('serial_number', models.CharField(default=uuid.uuid4, max_length=200)),
            ],
        ),
    ]
