# Generated by Django 4.0.6 on 2022-07-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(max_length=70)),
                ('InstallationDate', models.DateTimeField()),
                ('Latitude', models.IntegerField(default=100)),
                ('Longitude', models.IntegerField(default=100)),
            ],
        ),
    ]
