# Generated by Django 4.1 on 2022-08-24 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', 's__myMigration__1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressurereading',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 19, 6, 41, 962994, tzinfo=datetime.timezone.utc), verbose_name='date installation'),
        ),
    ]
