# Generated by Django 4.1 on 2022-08-24 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressureSensorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.pressuresensor')),
            ],
        ),
        migrations.CreateModel(
            name='Stag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=' ', max_length=200)),
                ('pressure_sensor', models.ManyToManyField(through='sensor.PressureSensorTag', to='sensor.pressuresensor')),
            ],
        ),
        migrations.AddField(
            model_name='pressuresensortag',
            name='stag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.stag'),
        ),
        migrations.CreateModel(
            name='PressureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2022, 8, 24, 18, 1, 13, 8269, tzinfo=datetime.timezone.utc), verbose_name='date installation')),
                ('value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('raw_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('sensor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensor.pressuresensor')),
            ],
        ),
    ]
