# Generated by Django 4.0.6 on 2022-07-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensor',
            new_name='PressureSensor',
        ),
    ]
