# Generated by Django 4.0.1 on 2022-09-07 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_alter_pressurereading_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressurereading',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 17, 35, 47, 63416, tzinfo=utc), verbose_name='date installation'),
        ),
        migrations.AlterField(
            model_name='pressuresensor',
            name='installation_date',
            field=models.DateField(default=datetime.date(2022, 9, 7), verbose_name='date installation'),
        ),
        migrations.AlterField(
            model_name='stag',
            name='pressure_sensor',
            field=models.ManyToManyField(through='sensor.PressureSensorTag', to='sensor.PressureSensor'),
        ),
    ]
