# Generated by Django 4.1 on 2022-08-24 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_pressuresensortag_stag_pressuresensortag_stag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressurereading',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 18, 10, 15, 179336, tzinfo=datetime.timezone.utc), verbose_name='date installation'),
        ),
    ]
