# Generated by Django 4.0.6 on 2022-07-27 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_rename_sensor_pressuresensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('Value', models.IntegerField(default=0)),
                ('SensorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.pressuresensor')),
            ],
        ),
    ]
