# Generated by Django 4.0.6 on 2022-07-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_pressurereading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressurereading',
            name='Value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pressuresensor',
            name='Latitude',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='pressuresensor',
            name='Longitude',
            field=models.FloatField(default=100),
        ),
    ]
