# Generated by Django 4.1 on 2022-08-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_alter_pressurereading_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressuresensor',
            name='PressureSensor_Id',
            field=models.CharField(auto_created=True, max_length=5, null=True),
        ),
    ]
