# Generated by Django 4.1 on 2022-08-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_pressuresensor_pressuresensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressuresensor',
            name='PressureSensor_Id',
            field=models.CharField(auto_created=True, max_length=20, null=True),
        ),
    ]
