# Generated by Django 4.1 on 2022-08-11 08:36

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0008_alter_pressuresensor_pressuresensor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressuresensor',
            name='InstallationDate',
        ),
        migrations.RemoveField(
            model_name='pressuresensor',
            name='Label',
        ),
        migrations.RemoveField(
            model_name='pressuresensor',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='pressuresensor',
            name='Longitude',
        ),
        migrations.RemoveField(
            model_name='pressuresensor',
            name='PressureSensor_Id',
        ),
        migrations.AddField(
            model_name='pressuresensor',
            name='installation_date',
            field=models.DateField(default=datetime.date(2022, 8, 11), verbose_name='date installation'),
        ),
        migrations.AddField(
            model_name='pressuresensor',
            name='serial_number',
            field=models.CharField(default=uuid.uuid4, max_length=200),
        ),
        migrations.AddField(
            model_name='pressuresensor',
            name='label',
            field=models.CharField(default='PSSR', max_length=200),
        ),
        migrations.AddField(
            model_name='pressuresensor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='pressuresensor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
