# Generated by Django 4.1 on 2022-08-11 08:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0009_remove_pressuresensor_installationdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressurereading',
            name='DateTime',
        ),
        migrations.RemoveField(
            model_name='pressurereading',
            name='SensorId',
        ),
        migrations.RemoveField(
            model_name='pressurereading',
            name='Value',
        ),
        migrations.AddField(
            model_name='pressurereading',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 8, 47, 24, 429450, tzinfo=datetime.timezone.utc), verbose_name='date installation'),
        ),
        migrations.AddField(
            model_name='pressurereading',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensor.pressuresensor'),
        ),
        migrations.AddField(
            model_name='pressurereading',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
