# Generated by Django 4.1 on 2022-08-11 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0012_alter_pressurereading_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressurereading',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 11, 19, 31, 659805, tzinfo=datetime.timezone.utc), verbose_name='date installation'),
        ),
    ]
