# Generated by Django 4.1 on 2022-08-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='lable',
            field=models.SlugField(default=' ', max_length=200),
        ),
    ]
