# Generated by Django 4.1 on 2022-08-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fl_tags', '0002_alter_tag_lable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='lable',
            new_name='tag',
        ),
    ]
