# Generated by Django 4.1 on 2022-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_tags', '0003_rename_lable_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.SlugField(default=' ', max_length=200, verbose_name='label'),
        ),
    ]
