# Generated by Django 4.1 on 2022-08-11 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default='MyQuestion', max_length=200)),
                ('date_published', models.DateField(default=datetime.date(2022, 8, 11))),
            ],
        ),
    ]
