# Generated by Django 4.1 on 2022-08-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choise'),
    ]

    operations = [
        migrations.AddField(
            model_name='choise',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
    ]
