# Generated by Django 4.1 on 2022-08-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_choice_questionchoice_alter_question_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.question'),
        ),
    ]
